//! Generates a C header (`.h`) declaring every non-`extern` function in a
//! Kite program, for `kite build --lib` -- see `docs/c-interop.md`.
//!
//! Kite function signatures compile to plain C-ABI-compatible LLVM
//! `define`s already (no name mangling, and every parameter/return type
//! is restricted to a scalar -- see `sema.rs`'s module docs), so a C
//! program can call them directly once it has a prototype; this module
//! just writes that prototype out mechanically.

use crate::ast::{Program, TypeName};

/// Returns the full contents of a `<name>.h` header for every non-`extern`
/// function in `program` (functions *declared* `extern` are implemented
/// in C already, so they don't need a Kite-generated prototype).
pub fn generate_c_header(guard_name: &str, program: &Program) -> String {
    let mut out = String::new();
    let guard = format!("KITE_{}_H", sanitize_guard(guard_name));

    out.push_str("// Generated by `kite build --lib` -- do not edit by hand.\n");
    out.push_str("//\n// Declares every Kite function in this library so C code can call it\n");
    out.push_str("// directly. See docs/c-interop.md for the full story (type mapping,\n");
    out.push_str("// linking, and how to call C from Kite with `extern make ...`).\n\n");
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n#include <stdbool.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    for func in &program.functions {
        if func.is_extern {
            continue; // implemented in C already -- nothing to declare
        }
        let ret = c_type(
            func.declared_return_type
                .as_ref()
                .unwrap_or(&TypeName::Void),
        );
        let params: Vec<String> = if func.params.is_empty() {
            vec!["void".to_string()]
        } else {
            func.params
                .iter()
                .map(|p| format!("{} {}", c_type(&p.ty), p.name))
                .collect()
        };
        out.push_str(&format!("{ret} {}({});\n", func.name, params.join(", ")));
    }

    out.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    out.push_str(&format!("#endif // {guard}\n"));
    out
}

fn c_type(ty: &TypeName) -> String {
    match ty {
        TypeName::Int => "int64_t".to_string(),
        TypeName::Float => "double".to_string(),
        TypeName::Bool => "bool".to_string(),
        TypeName::String => "const char*".to_string(),
        // Enums are a plain integer tag at the ABI boundary -- see
        // `ast::TypeName::Enum`'s docs.
        TypeName::Enum(_) => "int64_t".to_string(),
        TypeName::Void => "void".to_string(),
        // A `ptr<T>` is genuinely just `T*` at the C ABI boundary --
        // see `docs/pointers.md`.
        TypeName::Ptr(inner) => format!("{}*", c_type(inner)),
        // Not reachable: sema rejects list/tuple/dict/struct parameters
        // and return types before codegen ever sees them (see
        // `sema.rs`'s `is_first_class_value`).
        TypeName::List(_) | TypeName::Tuple(_) | TypeName::Dict(_) | TypeName::Struct(_) => {
            "void*".to_string()
        }
    }
}

fn sanitize_guard(name: &str) -> String {
    name.to_uppercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
