//! Project management: the `kite.toml` manifest format and helpers for
//! locating/loading a Kite project from disk, mirroring how `Cargo.toml`
//! anchors a Cargo project.

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub const MANIFEST_FILE: &str = "kite.toml";
pub const LOCK_FILE: &str = "kite.lock";
pub const SOURCE_DIR: &str = "src";
pub const MAIN_FILE: &str = "main.ki";
pub const BUILD_DIR: &str = "target";
pub const CACHE_DIR: &str = ".kite-cache";

#[derive(Debug, Serialize, Deserialize)]
pub struct Manifest {
    pub package: PackageSection,
    #[serde(default)]
    pub build: BuildSection,
    /// `name -> version requirement` (e.g. `"1.2.0"` or `"*"`).
    ///
    /// Kite v0.1's package manager (`kite add`/`remove`/`update`) manages
    /// this table and a local `.kite-cache/` directory, but there is no
    /// package *registry* to resolve against yet -- no network fetch, no
    /// real dependency-graph resolution, no compilation of downloaded
    /// dependency sources. That isn't implemented yet.
    /// `kite add` records the request; `kite build` does not yet do
    /// anything with it.
    #[serde(default)]
    pub dependencies: BTreeMap<String, String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct PackageSection {
    pub name: String,
    pub version: String,
    #[serde(default = "default_edition")]
    pub edition: String,
}

fn default_edition() -> String {
    "2026".to_string()
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BuildSection {
    /// Optimization level passed to clang: 0-3.
    #[serde(default = "default_opt_level")]
    pub opt_level: u8,
    /// Default target triple; `None` means "host".
    #[serde(default)]
    pub target: Option<String>,
}

impl Default for BuildSection {
    fn default() -> Self {
        Self {
            opt_level: default_opt_level(),
            target: None,
        }
    }
}

fn default_opt_level() -> u8 {
    0
}

impl Manifest {
    pub fn new(package_name: &str) -> Self {
        Self {
            package: PackageSection {
                name: package_name.to_string(),
                version: "0.1.0".to_string(),
                edition: default_edition(),
            },
            build: BuildSection::default(),
            dependencies: BTreeMap::new(),
        }
    }

    pub fn to_toml_string(&self) -> Result<String> {
        let mut deps = String::new();
        if self.dependencies.is_empty() {
            deps.push_str("# Run `kite add <package>` to add one.\n");
        } else {
            for (name, version) in &self.dependencies {
                deps.push_str(&format!("{name} = \"{version}\"\n"));
            }
        }
        Ok(format!(
            "[package]\nname = \"{}\"\nversion = \"{}\"\nedition = \"{}\"\n\n\
             [build]\nopt_level = {}\n\n\
             [dependencies]\n{deps}",
            self.package.name, self.package.version, self.package.edition, self.build.opt_level
        ))
    }

    pub fn load(path: &Path) -> Result<Manifest> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read manifest at {}", path.display()))?;
        let manifest: Manifest = toml::from_str(&text)
            .with_context(|| format!("failed to parse manifest at {}", path.display()))?;
        Ok(manifest)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        std::fs::write(path, self.to_toml_string()?)
            .with_context(|| format!("failed to write manifest at {}", path.display()))?;
        Ok(())
    }
}

/// `kite.lock`: records the exact dependency versions Kite last resolved.
/// v0.1 has no registry to resolve against (see [`Manifest::dependencies`]
/// docs), so this simply mirrors the manifest's version requirements
/// verbatim -- a placeholder for real resolved-version pinning once a
/// registry exists.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Lockfile {
    pub package: BTreeMap<String, String>,
}

impl Lockfile {
    pub fn from_manifest(manifest: &Manifest) -> Self {
        Self {
            package: manifest.dependencies.clone(),
        }
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let mut out = String::from(
            "# This file is automatically generated by `kite`.\n# Do not edit it by hand.\n\n",
        );
        for (name, version) in &self.package {
            out.push_str(&format!(
                "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n\n"
            ));
        }
        std::fs::write(path, out)
            .with_context(|| format!("failed to write lockfile at {}", path.display()))?;
        Ok(())
    }
}

/// A located Kite project on disk: its root directory and parsed manifest.
pub struct Project {
    pub root: PathBuf,
    pub manifest: Manifest,
}

impl Project {
    /// Searches `start_dir` and its ancestors for a `kite.toml`, the same
    /// way Cargo walks up looking for `Cargo.toml`.
    pub fn discover(start_dir: &Path) -> Result<Project> {
        let mut dir = start_dir.to_path_buf();
        loop {
            let candidate = dir.join(MANIFEST_FILE);
            if candidate.is_file() {
                let manifest = Manifest::load(&candidate)?;
                return Ok(Project {
                    root: dir,
                    manifest,
                });
            }
            if !dir.pop() {
                bail!(
                    "could not find `{MANIFEST_FILE}` in `{}` or any parent directory\n\
                     (run `kite init` to create a new project)",
                    start_dir.display()
                );
            }
        }
    }

    pub fn main_source_path(&self) -> PathBuf {
        self.root.join(SOURCE_DIR).join(MAIN_FILE)
    }

    pub fn manifest_path(&self) -> PathBuf {
        self.root.join(MANIFEST_FILE)
    }

    pub fn lock_path(&self) -> PathBuf {
        self.root.join(LOCK_FILE)
    }

    pub fn cache_dir(&self) -> PathBuf {
        self.root.join(CACHE_DIR)
    }

    pub fn build_dir(&self) -> PathBuf {
        self.root.join(BUILD_DIR)
    }

    pub fn output_binary_path(&self) -> PathBuf {
        self.build_dir().join(&self.manifest.package.name)
    }
}
